Models/ErrorViewModel.cs
using System;

namespace Turnos.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Especialidad.cs
using System.ComponentModel.DataAnnotations;

namespace Turnos.Models
{
    public class Especialidad
    {
        //A continuacion definimos las propiedades
        [Key] //Con  esto le indicamos al entityFramework que el siguiente metodo es un primary key
        public int idEspecialidad //Esta sera la primary key de nuestra tabla
        {
            get;
            set;
        }

        //Lo siguiente es la descripcion de la especialidad...
        public string Descripcion
        {
            get;
            set; 
        }
    }
}

Models/TurnosContext.cs
using Microsoft.EntityFrameworkCore;

namespace Turnos.Models
{
    public class TurnosContext : DbContext
    {
        //A continuacion tenemos el constructor, la misma tiene parametros por default para que los inicialice en el mismo
        //basandose en las propiedades de nuestra clase TurnosContext.
        // Con base(opciones) lo que hacemos es  heredar las opciones de base a TurnosContext

        public TurnosContext(DbContextOptions<TurnosContext> opciones):base(opciones) 
        {

        }

        //A continuacion definimos un objeto entidad que es del tipo DbSet, este es una tabla, de la manera que esta definido
        //definimos que es del tipo especialidad. Este va a ser el nombre final de la tabla en nuestro motor SQL Server.
        public DbSet<Especialidad> Especialidad {get; set;}
    }
}

Controllers/EspecialidadController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Turnos.Models;

namespace Turnos.Controllers
{
    public class EspecialidadController : Controller
    {
        //Constructor de la clase
        //Lo siguiente es una variable privada de solo lectura del tipo TurnosContext y la misma va a tener un objeto llamado _context
        private readonly TurnosContext _context;
        
        //A continuacion para que el constructor conecte al modelo, debemos pasarle el mismo y el tipo de objeto. 
        //de esta manera enviariamos a travez del controlador los elementos a la vista para que esta lo ejecute.
        public EspecialidadController(TurnosContext context)
        {
            _context = context;
        }

        //El siguiente metodo muestra los datos en la pantalla del usuario
        //IActionResult retorna la informacion contenida dentro del metodo a la vista del usuario, en este caso index

        public IActionResult Index()
        {

            //Lo siguiente indica que al resultado de este metodo lo retorna a la vista index, lo que devolvemos es un objeto del tipo
            //_context, el mismo va a acceder a la tabla especialidad y a travez de ToList seleccionamos toda la tabla para tomar sus valores
            //similar al select*
            return View(_context.Especialidad.ToList());
        }

        //Agregamos el metodo editar

        public IActionResult Edit(int? Id)
        {
            if(Id == null)
            {
                return NotFound();
            }
            var especialidad = _context.Especialidad.Find(Id);

            if(especialidad == null)
            {
                return NotFound();
            }
            return View(especialidad);
        }

        //El siguiente metodo editar cumple la funcion de POST, es decir va a recibir el parametro Id del turno para darnos la posibilidad
        //de editar.
        [HttpPost]
        public IActionResult Edit(int Id, [Bind("idEspecialidad,Descripcion")]Especialidad especialidad)
        {
            if(Id != especialidad.idEspecialidad)
            {
                return NotFound();
            }
        //Lo siguiente es para que, si el enlace a traves de bind a la base de datos fue correcto y todos sus elementos concuerdan con la base
        //quiere decir que estamos en condiciones de grabar nuestros datos.
            if(ModelState.IsValid)
            {
                //A continuacion pasamos los datos a nuestra vista index una vez guardada la informacion en nuestra BD
                _context.Update(especialidad);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(especialidad);
        }

        public IActionResult Delete(int? id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            //De la siguiente manera ingresamos a nuestro campo especialidad y a traves del metodo 
            //FirstOrDefault va a encontrar la primer coincidencia que se asimile al id que ingresa como parametro Y en el caso que no 
            //retorne nada devuelve default.

            var especialidad = _context.Especialidad.FirstOrDefault(e => e.idEspecialidad == id);
            //En el caso que no exista la especialidad devuelve NotFound a traves de la sig validacion
            if(especialidad == null)
            {
                return NotFound();
            }
            return View(especialidad);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var especialidad = _context.Especialidad.Find(id);
            _context.Especialidad.Remove(especialidad);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Turnos.Models;

namespace Turnos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Especialidad/Delete.cshtml
@model Turnos.Models.Especialidad

<h3>
    ¿Esta usted seguro de eliminar el siguiente registro?
</h3>

<div>
    @*Esta etiqueta nos permite agregar descripciones de algun elemento*@
    <dl>
        <dt>
            @Html.DisplayNameFor(modelo => modelo.Descripcion)
        </dt>
        @*La siguiente es la etiqueta descripcion data*@
        <dd>
            @Html.DisplayFor(modelo => modelo.Descripcion)
        </dd>
    </dl>
    <form asp-action="Delete">
    <input type="hidden" asp-for="idEspecialidad">
    <input type="submit" value="Eliminar">
    </form>
    @*Por si nos arrepentimos de borrar el registro*@
    <div>
        <a asp-action="index">Volver</a>
    </div>
</div>

Views/Especialidad/Edit.cshtml
@model Turnos.Models.Especialidad

<h1>Especialidad</h1>

<div>
    @*De esta manera estamos indicandole a la vista que la accion del formulario se aplica sobre el metodo Edit*@
    <form asp-action="Edit">
        @*Esta etiqueta sirve para validar los elementos dentro del formulario, por ejemplo verificar si colocaron un elemento vacio*@
        <div asp-validation-summary="ModelOnly"></div>
        @*Lo siguiente trae el dato del ID*@
        <input type="hidden" asp-for="idEspecialidad">
        <div>
            @*Lo siguiente hace que, primero guarda la informacion de la descripcion en un label
            segundo toma ese dato descripcion y lo coloca en un input para que lo podamos editar
            tercero valida por medio de span y en conexion en el validation-summary encima que 
            pongamos contenido en el input antes de grabar*@
            <label asp-for="Descripcion"></label>
            <input asp-for="Descripcion"/>
            <span asp-validation-for="Descripcion"></span>
        </div>
        <div>
            @*agregamos el boton para grabar*@
            <input type="submit" value="Grabar"/>
        </div>

    </form>

</div>
<div>
    @*Para volver a la vista principal*@
    <a asp-action="Index">Volver</a>
</div>

Views/Especialidad/Index.cshtml
@* Agregamos la referencia a este modelo y la definimos con una estructura Enumerable, para que esta estructura sea
iterable
Enumerable permite ver registro por registro de la tabla para luego mostrarlo. *@
@model IEnumerable<Turnos.Models.Especialidad>

    <table>
        @*Sobre el THEAD definimos el encabezado de la tabla*@
        <thead>
            <tr>
                <th>
                    @*Con lo siguiente hacemos un despliegue HTML con el elemento descripcion del modelo*@
                    @Html.DisplayNameFor(model => model.Descripcion)
                </th>
            </tr>
        </thead>
        <tbody>
            @*Aqui colocaremos el codigo para mostrar los registros sobre la base de datos*@
            @*A continuacion recorremos con un ciclo los elementos de la base de datos*@
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Descripcion)
                </td>
                @*Hacemos un link a la vista de editar*@
                <td>
                    <a asp-action="Edit" asp-route-id="@item.idEspecialidad">Editar</a>
                </td>
            </tr>
            }
        </tbody>
    </table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Turnos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Turnos</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Especialidad"
                                asp-action="Index">Especialidad</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    @*La siguiente funcion es muy importante, ejecuta la vista que esta en este momento y la renderiza dentro de un
    contenedor padre*@
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    @*Aqui tenemos los detalles de la aplicacion*@
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Turnos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>